accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.SignUpView.as_view(), name='signup'),
]

app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.detail, name='detail'),
    path('new', views.new, name='new'),
    path('<int:id>/new_com',views.new_com, name='new_com'),
    path('create', views.create, name='create'),
    path('create_com',views.create_com,name='create_com'),
    path('<int:id>/edit', views.edit, name='edit'),
    path('<int:id>/update', views.update, name='update'),
    path('<int:id>/delete', views.delete, name='delete'),
]

mymemories/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('',RedirectView.as_view(url='/app')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

app/models.py
from django.db import models
from datetime import datetime

# Create your models here.
"""
class Dbtest(models.Model):
    text = models.CharField(max_length=100)
    number = models.IntegerField()
    name = models.CharField(max_length=50,null=True)

    def __str__(self):
        return f'{self.text} ,{self.number} ,{self.name}'
"""
class Thread(models.Model):
    #タイトル
    title = models.CharField('タイトル',max_length=200,blank=False)
    #メッセージ
    message = models.TextField('メッセージ',blank=False)
    #登録日時
    pub_data = models.DateTimeField('登録日時',auto_now_add=True,editable=False)

    class Meta:
        verbose_name_plural = 'スレッド'
    
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    #スレッド
    title = models.ForeignKey(Thread,verbose_name='スレッド',on_delete=models.CASCADE)
    #メッセージ
    message = models.CharField('メッセージ',max_length=200, blank=False)
    #登録日時
    pub_data = models.DateTimeField('登録日時',auto_now_add=True,editable=False)

    class Meta:
        verbose_name_plural = 'コメント'
        ordering = ('title', ) # nameで昇順ソート
    
    def __str__(self):
        return '{} {}'.format(self.title, self.message)

app/forms.py
from datetime import datetime
from django import forms
from .models import Thread,Comment

class SearchForm(forms.Form):
    keyword = forms.CharField(label='検索', max_length=200)

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Thread
        fields = ('title','message')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('title', 'message')

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Thread,Comment
from django.db.models import Q
from .forms import SearchForm,ArticleForm,CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin

def index(request):
    searchForm = SearchForm(request.GET)
    if searchForm.is_valid():
        keyword = searchForm.cleaned_data['keyword']
        #articles = Dbtest.objects.filter(text__contains=keyword)
        # articles = Thread.objects.filter(Q(text__contains=str(keyword)) | Q(text__contains=str(keyword)))
        articles = Thread.objects.filter(Q(title__contains=str(keyword)))
    else:
        searchForm = SearchForm()
        articles = Thread.objects.all()

    context = {
        'articles': articles,
        'searchForm': searchForm,
    }
    return render(request, 'app/index.html', context)

def detail(request, id):
    article = get_object_or_404(Thread, pk=id)
    
    # comment = Comment.objects.all()
    # comment = Comment.objects.select_related('title_id').get(id=id)
    comments = Comment.objects.filter(title_id=id)
    
    context = {
        'message': 'Show Article ' + str(id),
        'article': article,
        'comments':comments,
    }

    return render(request, 'app/detail.html', context)

def new(request):
    articleForm = ArticleForm()

    context = {
        'message': 'New Article',
        'articleForm': articleForm,
    }
    return render(request, 'app/new.html', context)

def new_com(request, id):
    commentForm = CommentForm()
    article = Thread.objects.get(id=id)
    
    context = {
        'message': '新規コメント',
        'commentForm': commentForm,
        'article':article,
    }
    return render(request,'app/new_com.html',context)
    
def create(request):
    articles = Thread.objects.all()
    if request.method == 'POST':
        articleForm = ArticleForm(request.POST)
        
        if articleForm.is_valid():
            articles = articleForm.save()
            articles.save()

    context = {
        'article':articles,
    }
    return render(request, 'app/detail.html', context)
    #本当はdetail画面に移り変わってからではなく直接indexに画面遷移をしたかった。

def create_com(request):
    comments = Comment.objects.all()
    if request.method == 'POST':
        commentForm = CommentForm(request.POST)
        article_id = request.POST.get("title")
        if commentForm.is_valid():
            comment= commentForm.save()

    article = get_object_or_404(Thread, pk=article_id)
    comments = Comment.objects.filter(title_id=article_id)
    context = {
        #'message': 'Create article ' + str(comment.id),
        'article': article,
        'comments': comments,
    }
    return render(request, 'app/detail.html', context)

def edit(request, id):
    return HttpResponse('this is edit ' + str(id))

def update(request, id):
    return HttpResponse('this is update ' + str(id))

def delete(request, id):
    article = get_object_or_404(Thread, pk=id)
    article.delete()

    articles = Thread.objects.all()
    context = {
        'message': 'Delete article ' + str(id),
        'articles': articles,
    }
    return render(request, 'app/index.html', context)

accounts/templates/accounts/signup.html
{% extends 'layout.html'%}

{%block content%}
<h1> Sing Up </h1>
<section class ='common-form'>
    <form method='post'>
        {% csrf_token%}
        {{form.as_p}}
        <button type='submit'>Sign up</button>
    </form>
</section>
{% endblock %}

app/templates/app/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <title>app</title>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
        <style>body {padding-top: 80px;}</style>
        
    </head>
    <body>
        <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "app:index" %}'>app</a>
        </nav>
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

app/templates/app/detail.html
{% extends 'layout.html' %}
{% block content %}
<p>&nbsp;</p>
<h1><span style="background-color:#00FF00;">{{ article.title }}</span></h1>
<div class='text-right'>
    <a href='{% url "app:new_com" article.id %}' class='btn btn-outline-primary'>新規コメント</a>
    </div>
    <p>&nbsp;</p>
     {{ article.message }}
     <p>&nbsp;</p>

    {% for comment in comments %}
    <div style="margin: 10px 20px 0 0; background-color: rgba(0, 0, 0, 0.2); padding: 8px 16px; border-radius: 15px; border: 1px solid black;">
        
        <p style="font-size: 18px; color: black; ">
            <span style="color: green; font-weight: bold;">{{ comment.id }}. 名無しがお送りします</span>
            <br>
            {{comment.message}}</p>
        <div style="text-align: end;">
        <span >{{ comment.pub_data }}</span>
        </div>
    </div>
     {% endfor %}
     
{% endblock %}

app/templates/app/index.html
{% extends 'layout.html' %}
{% block content %}
    <h1>最近投稿された記事</h1>

    {% if searchForm %}
        <form action='{% url "app:index" %}' method='get'>
            <div class='form-group'>
                {{ searchForm }}
                <input type='submit' class='btn btn-outline-primary' value='検索'>
                <a href='{% url "app:index" %}' class='btn btn-outline-secondary'>クリア</a>
        </div>
        <div class='text-right'>
        <a href='{% url "app:new" %}' class='btn btn-outline-primary'>新規スレッド</a>
        </div>
        </form>
        <p>&nbsp;</p>
    {% endif %}

    <table  class='table table-striped table-hover'>
        <th>スレッド名</th>
        <th>コメント</th>
        <th>登録日時</th>
        {% for article in articles %}
            <tr>
                <td><a href = '{% url "app:detail" article.id %}'>{{ article.title }}</a></td>
                <td>{{ article.message }}</td>
                <td>{{ article.pub_data}}</td>
                <!--
                <td>
                    <a href='{% url "app:detail" article.id %}' class='btn btn-outline-primary'>詳細</a>
                    <a href='{% url "app:delete" article.id %}' class='btn btn-outline-secondary'>削除</a>
                </td>
                -->
            </tr>
        {% endfor %}
    </table>
    
    <!--{% if user.is_authenticated %} 
    <div>
        <a href='{% url "app:new" %}' class='btn btn-outline-primary'>新規スレッド</a>
    </div>
   {% endif %}-->
{% endblock %}

app/templates/app/new.html
{% extends 'layout.html' %}
{% load bootstrap4 %}

{% block content %}
    <h1>{{ message }}</h1>

    <form action='{% url "app:create" %}' method='post' class='form'>
        {% csrf_token %}
        {% bootstrap_form articleForm layout='horizontal' %}
        <button type='submit' class='btn btn-outline-primary'>作成する</button>
        <a href='{% url "app:index" %}' class='btn btn-outline-secondary'>戻る</a>
    </form>
{% endblock %}

app/templates/app/new_com.html
{% extends 'layout.html' %}
{% load bootstrap4 %}

{% block content %}
    <h1>{{ message }}</h1>

    <form action='{% url "app:create_com" %}' method='post' class='form'>
        {% csrf_token %}
       <!--{% bootstrap_form commentForm layout='horizontal' %}
       -->
       
      
        <label style="font-size: 36px; font-weight: bold; margin-top: 30px;">書き込むスレッド</label>
        <br>
        <span style="font-size: 32px; font-weight: semi-bold;">{{ article.title }} </span>
        <br>
       <label for="comment" style="font-size: 36px; font-weight: bold; margin-top: 30px;">コメントを入力</label>
       <br>
       <textarea placeholder="コメントを入力してください" cols="100" rows="10"
       name="message"></textarea>
  <br>
  <input type="text" value={{article.id}} name="title" readonly hidden />
        <button type='submit' class='btn btn-outline-primary'>作成する</button>
        <!-- <a href='{{request.META.HTTP_REFERER}}' class='btn btn-outline-secondary'>戻る</a> -->
        <a href='{% url "app:detail"  article.id %}'>戻る</a>
    </form>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <title>{%block title%} {% endblock%}</title>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <style>
          body {
            padding-top: 80px;
          }
        </style>

    </head>
    <body>
        <nav class='navbar navbar-expand-sm navbar-dark bg-primary fixed-top justify-content-center nav.sticky-top'>
            <a class='navbar-brand ' href='{% url "app:index" %}'>考察マニア</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav">
                  <li class="nav-item active">
                    <a class="nav-link" href="#">掲示板</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">ライター記事</a>
                  </li>
                  <!-- ドロップダウンタイプ 
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Dropdown link
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                -->
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">人気掲示板</a>
                  </li>
              </div>
        </nav>
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>